version: '3'
services:
    database:
        image: postgres:13.0
        restart: always
        environment:
            POSTGRES_USER: nanny
            POSTGRES_PASSWORD: nanny
            POSTGRES_DB: nanny
        ports:
            - 5432:5432
