version: "3.3"
services:

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: nanny
      POSTGRES_USER: nanny
      POSTGRES_PASSWORD: nanny
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nanny"]
      interval: 5s
      timeout: 2s
      retries: 10
      
  db_test:
    image: postgres:12
    environment:
      POSTGRES_DB: nanny_test
      POSTGRES_USER: nanny_test
      POSTGRES_PASSWORD: nanny_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nanny_test"]
      interval: 5s
      timeout: 2s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nanny.fr
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "5050:80"
